In [54]:
import pandas as pd

In [ ]:
train_df = pd.read_csv('../../data/processed/train.csv')
val_df = pd.read_csv('../../data/processed/val.csv')
test_df = pd.read_csv('../../data/processed/test.csv')
train_df.shape, val_df.shape, test_df.shape

((172064, 65), (43016, 65), (53770, 65))

In [56]:
import pandas as pd

df = pd.concat([train_df, val_df, test_df], axis=0, ignore_index=True)
df.shape

(268850, 65)

In [57]:
drop_cols = ['serviceCharge', 'picturecount', 'yearConstructed', 'pricetrend', 'baseRent', 'regio2_freq', 'numberOfFloors', 'floor']
df.drop(columns=drop_cols, inplace=True)

In [58]:
df['rent_level'] = pd.qcut(df['totalRent'], q=3, labels=['low','medium','high'])
df['space_level'] = pd.qcut(df['livingSpace'], q=3, labels=['small','medium','large'])
df['room_level'] = pd.qcut(df['noRooms'], q=3, labels=['few','medium','many'])
# One-hot encode
df = pd.get_dummies(df, columns=['rent_level','space_level','room_level'])

df.drop(columns=['totalRent', 'livingSpace', 'noRooms'], inplace=True)

In [59]:
df = df.astype('bool')
df.dtypes

newlyConst            bool
balcony               bool
hasKitchen            bool
cellar                bool
lift                  bool
                      ...
space_level_medium    bool
space_level_large     bool
room_level_few        bool
room_level_medium     bool
room_level_many       bool
Length: 63, dtype: object

In [62]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, 
                           min_support=0.05,   # có thể chỉnh
                           use_colnames=True)

frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)
frequent_itemsets

      support                                           itemsets
3    0.640636                                           (cellar)
1    0.616455                                          (balcony)
33   0.447298                                   (room_level_few)
39   0.435555                                  (balcony, cellar)
34   0.408555                                (room_level_medium)
..        ...                                                ...
368  0.050351         (balcony, rent_level_medium, cellar, lift)
234  0.050288    (balcony, condition_unknown, rent_level_medium)
349  0.050218  (typeOfFlat_unknown, room_level_few, space_lev...
68   0.050199           (regio1_nordrhein_westfalen, hasKitchen)
189  0.050147                        (balcony, lift, newlyConst)

[405 rows x 2 columns]

In [74]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, 
                          metric="confidence", 
                          min_threshold=0.6)

rules = rules[
    (rules['lift'] > 2) &
    (rules['confidence'] > 0.7) &
    (rules['support'] > 0.05)
]

rules = rules.sort_values(by='lift', ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
171,"(regio1_sachsen, space_level_small)","(room_level_few, rent_level_low)",0.094298,0.225933,0.072405,0.767829,3.398486,1.0,0.051100,3.334039,0.779231,0.292159,0.700064,0.544150
346,"(balcony, newlyConst)",(lift),0.068034,0.235529,0.050147,0.737084,3.129481,1.0,0.034123,2.907660,0.730132,0.197883,0.656081,0.474998
279,(newlyConst),(lift),0.078747,0.235529,0.055563,0.705588,2.995756,1.0,0.037015,2.596601,0.723139,0.214765,0.614881,0.470747
328,"(balcony, rent_level_high, room_level_many)",(space_level_large),0.058267,0.333323,0.051627,0.886052,2.658234,1.0,0.032206,5.850694,0.662407,0.151862,0.829080,0.520469
201,"(rent_level_high, room_level_many)",(space_level_large),0.074302,0.333323,0.065817,0.885813,2.657518,1.0,0.041051,5.838462,0.673771,0.192557,0.828722,0.541635
311,"(room_level_few, hasKitchen, rent_level_low)",(space_level_small),0.061350,0.333465,0.052933,0.862799,2.587376,1.0,0.032475,4.858079,0.653607,0.154828,0.794157,0.510767
303,"(room_level_few, condition_unknown, rent_level...",(space_level_small),0.063028,0.333465,0.053327,0.846090,2.537271,1.0,0.032310,4.330690,0.646631,0.155398,0.769090,0.503004
299,"(regio1_sachsen, cellar, space_level_small)",(rent_level_low),0.062752,0.336939,0.053450,0.851757,2.527929,1.0,0.032306,4.472813,0.644888,0.154372,0.776427,0.505196
167,"(room_level_few, regio1_sachsen, space_level_s...",(rent_level_low),0.085557,0.336939,0.072405,0.846274,2.511656,1.0,0.043577,4.313273,0.658167,0.206817,0.768158,0.530582
139,"(regio1_sachsen, space_level_small)",(rent_level_low),0.094298,0.336939,0.079401,0.842024,2.499042,1.0,0.047629,4.197235,0.662300,0.225677,0.761748,0.538839
26,"(room_level_few, rent_level_low)",(space_level_small),0.225933,0.333465,0.186011,0.823302,2.468932,1.0,0.110670,3.772168,0.768624,0.498172,0.734900,0.690557
313,"(hasKitchen, rent_level_low)","(room_level_few, space_level_small)",0.074287,0.290902,0.052933,0.712548,2.449442,1.0,0.031323,2.466836,0.639230,0.169518,0.594622,0.447254
74,"(room_level_few, cellar, rent_level_low)",(space_level_small),0.137612,0.333465,0.112048,0.814228,2.441722,1.0,0.066159,3.587924,0.684672,0.312085,0.721287,0.575119
148,"(balcony, room_level_few, rent_level_low)",(space_level_small),0.094268,0.333465,0.075856,0.804688,2.413111,1.0,0.044421,3.412660,0.646546,0.215577,0.706973,0.516084
325,"(room_level_few, condition_well_kept, rent_lev...",(space_level_small),0.064337,0.333465,0.051717,0.803839,2.410566,1.0,0.030262,3.397896,0.625396,0.149433,0.705700,0.479464
168,"(room_level_few, regio1_sachsen, rent_level_low)",(space_level_small),0.090768,0.333465,0.072405,0.797689,2.392123,1.0,0.042137,3.294604,0.640058,0.205796,0.696473,0.507409
321,"(balcony, room_level_few, cellar, rent_level_low)",(space_level_small),0.064880,0.333465,0.051735,0.797397,2.391249,1.0,0.030100,3.289863,0.622175,0.149261,0.696036,0.476271
228,"(room_level_few, cellar, regio1_sachsen)",(rent_level_low),0.079118,0.336939,0.060882,0.769498,2.283793,1.0,0.034223,2.876601,0.610428,0.171412,0.652367,0.475094
275,"(hasKitchen, rent_level_low)",(space_level_small),0.074287,0.333465,0.056399,0.759213,2.276741,1.0,0.031627,2.768152,0.605777,0.160521,0.638748,0.464172
103,"(room_level_few, regio1_sachsen)",(rent_level_low),0.119189,0.336939,0.090768,0.761547,2.260193,1.0,0.050609,2.780674,0.633007,0.248435,0.640375,0.515469
100,"(balcony, room_level_medium, rent_level_high)",(space_level_large),0.123686,0.333323,0.092739,0.749797,2.249458,1.0,0.051512,2.664543,0.633846,0.254590,0.624701,0.514012
191,"(balcony, room_level_medium, rent_level_high, ...",(space_level_large),0.090210,0.333323,0.067636,0.749763,2.249356,1.0,0.037567,2.664180,0.610502,0.190044,0.624650,0.476339
130,"(balcony, room_level_many)",(space_level_large),0.108064,0.333323,0.080275,0.742849,2.228614,1.0,0.044255,2.592552,0.618083,0.222300,0.614280,0.491841
238,"(balcony, cellar, room_level_many)",(space_level_large),0.080115,0.333323,0.059490,0.742560,2.227746,1.0,0.032786,2.589639,0.599114,0.168077,0.613846,0.460518
84,(room_level_many),(space_level_large),0.144147,0.333323,0.106238,0.737008,2.211089,1.0,0.058190,2.534967,0.639987,0.286175,0.605518,0.527865
136,"(room_level_medium, cellar, rent_level_high)",(space_level_large),0.107863,0.333323,0.079464,0.736715,2.210211,1.0,0.043511,2.532149,0.613756,0.219683,0.605078,0.487558
67,"(room_level_medium, rent_level_high)",(space_level_large),0.158735,0.333323,0.116764,0.735589,2.206833,1.0,0.063854,2.521366,0.650047,0.311126,0.603390,0.542946
159,"(cellar, room_level_many)",(space_level_large),0.100309,0.333323,0.073305,0.730792,2.192441,1.0,0.039870,2.476437,0.604527,0.203440,0.596194,0.475357
344,"(typeOfFlat_unknown, room_level_few)",(space_level_small),0.069942,0.333465,0.050218,0.717986,2.153108,1.0,0.026894,2.363479,0.575830,0.142183,0.576895,0.434289
118,"(room_level_few, regio1_sachsen)",(space_level_small),0.119189,0.333465,0.085557,0.717825,2.152628,1.0,0.045812,2.362138,0.607907,0.233064,0.576655,0.487198
271,"(room_level_few, cellar, regio1_sachsen)",(space_level_small),0.079118,0.333465,0.056537,0.714588,2.142919,1.0,0.030154,2.335344,0.579170,0.158792,0.571797,0.442066
218,"(space_level_small, lift)",(room_level_few),0.066134,0.447298,0.063128,0.954556,2.134050,1.0,0.033547,12.162186,0.569040,0.140190,0.917778,0.547844
123,"(room_level_few, condition_unknown)",(space_level_small),0.119531,0.333465,0.084315,0.705377,2.115297,1.0,0.044455,2.262334,0.598832,0.228692,0.557979,0.479111
338,"(balcony, space_level_small, hasKitchen)",(room_level_few),0.053926,0.447298,0.050895,0.943785,2.109971,1.0,0.026774,9.831997,0.556045,0.113016,0.898291,0.528784
86,"(space_level_small, hasKitchen)",(room_level_few),0.112706,0.447298,0.105996,0.940464,2.102546,1.0,0.055583,9.283498,0.590995,0.233467,0.892282,0.588717
312,"(space_level_small, hasKitchen, rent_level_low)",(room_level_few),0.056399,0.447298,0.052933,0.938535,2.098232,1.0,0.027706,8.992086,0.554693,0.117429,0.888791,0.528437
265,"(cellar, space_level_small, hasKitchen)",(room_level_few),0.062057,0.447298,0.057631,0.928674,2.076188,1.0,0.029873,7.748978,0.552643,0.127579,0.870951,0.528758
169,"(regio1_sachsen, space_level_small, rent_level...",(room_level_few),0.079401,0.447298,0.072405,0.911885,2.038652,1.0,0.036889,6.272480,0.553422,0.159378,0.840573,0.536878
119,"(regio1_sachsen, space_level_small)",(room_level_few),0.094298,0.447298,0.085557,0.907305,2.028414,1.0,0.043378,5.962599,0.559791,0.187609,0.832288,0.549290
272,"(regio1_sachsen, cellar, space_level_small)",(room_level_few),0.062752,0.447298,0.056537,0.900954,2.014216,1.0,0.028468,5.580275,0.537242,0.124665,0.820797,0.513676

In [69]:
rules_support = rules.sort_values(by='support', ascending=False)
rules_support

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(balcony),(cellar),0.616455,0.640636,0.435555,0.706548,1.102885,1.0,0.040632,1.224608,0.243224,0.530172,0.183412,0.693214
1,(cellar),(balcony),0.640636,0.616455,0.435555,0.679879,1.102885,1.0,0.040632,1.198125,0.259589,0.530172,0.165363,0.693214
2,(room_level_few),(space_level_small),0.447298,0.333465,0.290902,0.650354,1.950294,1.0,0.141744,1.906316,0.881590,0.593847,0.475428,0.761358
3,(space_level_small),(room_level_few),0.333465,0.447298,0.290902,0.872362,1.950294,1.0,0.141744,4.330234,0.731029,0.593847,0.769066,0.761358
4,(room_level_medium),(balcony),0.408555,0.616455,0.277757,0.679853,1.102842,1.0,0.025901,1.198025,0.157667,0.371704,0.165293,0.565212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,"(typeOfFlat_unknown, room_level_few)",(space_level_small),0.069942,0.333465,0.050218,0.717986,2.153108,1.0,0.026894,2.363479,0.575830,0.142183,0.576895,0.434289
345,"(typeOfFlat_unknown, space_level_small)",(room_level_few),0.057050,0.447298,0.050218,0.880232,1.967889,1.0,0.024699,4.614778,0.521599,0.110580,0.783305,0.496250
346,"(balcony, newlyConst)",(lift),0.068034,0.235529,0.050147,0.737084,3.129481,1.0,0.034123,2.907660,0.730132,0.197883,0.656081,0.474998
347,"(newlyConst, lift)",(balcony),0.055563,0.616455,0.050147,0.902530,1.464065,1.0,0.015895,3.935021,0.335618,0.080639,0.745872,0.491939
348,(newlyConst),"(balcony, lift)",0.078747,0.189399,0.050147,0.636815,3.362286,1.0,0.035232,2.231919,0.762638,0.230033,0.551955,0.450791